### PR TITLE
Roll back coupling in merge from `develop` + update tool privileges

### LINKED ISSUE #18: Decouple `magnify` and `mc_teacher`
Presently, `mc_teacher` is dependent on `magnify`, since part of its functionality (the Plant Compendium button) needs access to objects defined in and handled by `magnify`.

Ideally, `mc_teacher` should be able to run independent of `magnify`. I'm currently unsure of how the current systems in place could be refactored to make this possible, but hope to find some way to make it happen.

### PR DESCRIPTION
**Pull request by Lowie375**
This PR supercedes #33 and #34:
* Decouple `magnify` and `mc_teacher` (#18)
* Update magnifying tool privilege from `shout` to `interact`

### CODE REVIEW

**Comment by Lowie375** [comment]
Currently working on resolving conflicts (which seem to run the length of the entire file), will re-open this as ready for merging once they have been resolved

**Comment by Lowie375** [comment]
Have resolved merge conflicts - mainly had to do with whitespace and some differences between realm teleportation functions.
Would recommend that @lukasdragon checks this over before merging to ensure that the correct teleportation functions are present

Would recommend hiding whitespace in the diff view menu, since the whitespace changes in this PR greatly obfuscate the actual changes made

**Review by lukasgolson — CHANGES_REQUESTED** [review]
The formatting changed so much in the gui_dash.lua and init.lua that I can't readily determine what has changed (even with my local diffing tools); Could you either: A) give me line numbers with changes that are relevant to myself or B) Undo the init.lua and gui_dash.lua, and re-apply the changes without reformatting the source file. Thanks!

**Comment by Lowie375** [comment]
Conflicting diffs:
- [`mc_teacher/gui_dash.lua`](https://github.com/ubc-minetest-classroom/Minetest_Classroom/blob/magnify/mods/mc_teacher/gui_dash.lua) around lines [588](https://github.com/ubc-minetest-classroom/Minetest_Classroom/blob/magnify/mods/mc_teacher/gui_dash.lua#L588), [712](https://github.com/ubc-minetest-classroom/Minetest_Classroom/blob/magnify/mods/mc_teacher/gui_dash.lua#L712), and [852](https://github.com/ubc-minetest-classroom/Minetest_Classroom/blob/magnify/mods/mc_teacher/gui_dash.lua#L852)
- Pretty certain no realm-related code was changed in `mc_student/init.lua`

Other diffs that were merged in are at [61-64](https://github.com/ubc-minetest-classroom/Minetest_Classroom/blob/magnify/mods/mc_realmportals/portalhelper.lua#L61), [67](https://github.com/ubc-minetest-classroom/Minetest_Classroom/blob/magnify/mods/mc_realmportals/portalhelper.lua#L67), [74-82](https://github.com/ubc-minetest-classroom/Minetest_Classroom/blob/magnify/mods/mc_realmportals/portalhelper.lua#L74) in [`mc_realmportals/portalhelper.lua`](https://github.com/ubc-minetest-classroom/Minetest_Classroom/blob/magnify/mods/mc_realmportals/portalhelper.lua) - these are likely safe since they didn't conflict

**Comment by lukasgolson** [comment]
`mc_teacher/gui_dash.lua` looks good to me.

**Comment by Lowie375** [comment]
Will leave this branch open since it appears to be in an okay state now, but will see if I can create a cleaner copy that could be merged instead to avoid the gigantic formatting diff

**Comment by Lowie375** [comment]
Just fixed the formatting: the diffs on `mc_student/init.lua` and `mc_teacher/gui_dash.lua` should be easier to compare now!
Will make sure that I check the file line endings when I make commits from now on

**Pull request merged**
